name: Movies CI/CD pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Installing NPM
      run: npm install
    - name: Running untit tests
      run: npm run test:unit
    - name: Display softuni username
      run: echo "stefan147"
    
  deploy:
      needs: build
      runs-on: ubuntu-latest
      
      steps:
        - name: Deploy to production
          uses: johnbeynon/render-deploy-action@v0.0.8
          with:
            service-id: SERVICE_ID
            api-key: RENDER_TOKEN
  ui_tests:
      needs: deploy
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Use Node.js 18.x
          uses: actions/setup-node@v3
          with:
            node-version: 18.x
            cache: 'npm'
        - name: Installing NPM
          run: npm install
        - name: Installing playwright
          run: npx playwright install --with-deps
        - name: Start server
          run: npm run start
        - name: Running ui tests
          run: npm test:ui

